language: clojure
lein: lein2
before_script:
  - cp ./bin/ci/cassandra.yaml /etc/cassandra/ && /etc/init.d/cassandra restart && cassandra-cli -f ./bin/ci/before_build.cql
script: lein2 test :ci
services:
  - cassandra
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7